[package]
name = "restson"
version = "0.2.0"
authors = ["Sami Pietikäinen"]
description = "Easy-to-use REST client for Rust with automatic serialization and deserialization."
repository = "https://github.com/spietika/restson-rust"
keywords = ["rest", "client", "json", "hyper"]
categories = ["network-programming", "web-programming::http-client"]
readme = "README.md"
license = "MIT"

[dependencies]
hyper = "^0.11.22"
hyper-tls = "^0.1.2"
futures = "^0.1.18"
tokio-core = "^0.1.15"
serde = "^1.0.31"
serde_json = "^1.0.11"
serde_derive = "^1.0.31"
url = "^1.7.0"
log = "^0.4.1"
