[package]
name = "restson"
version = "0.0.1"
authors = ["Sami Pietikäinen"]
license = "MIT"

[dependencies]
hyper = "^0.11"
hyper-tls = "^0.1"
futures = "^0.1"
tokio-core = "^0.1"
serde = "^1.0"
serde_json = "1.0"
serde_derive = "^1.0"
url = "^1.0"
log = "^0.3"
