[package]
name = "restson"
version = "0.1.1"
authors = ["Sami Pietikäinen"]
description = "Easy-to-use REST client for Rust with automatic serialization and deserialization."
repository = "https://github.com/spietika/restson-rust"
keywords = ["rest", "client", "json", "hyper"]
readme = "README.md"
license = "MIT"

[dependencies]
hyper = "^0.11"
hyper-tls = "^0.1"
futures = "^0.1"
tokio-core = "^0.1"
serde = "^1.0"
serde_json = "1.0"
serde_derive = "^1.0"
url = "^1.0"
log = "^0.3"
